[package]
name = "rust-geo-alg"
version = "0.1.0"
authors = ["Saeed Kazemi <kazemi.ms@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"